theme: jekyll-theme-cayman
# Site settings
title_left    : "bobthe"
title_right   : "god78" # default: ""
description   : "My site."
keywords      : "Student"
url           : https://bobthegod78.github.io/ # site url
baseurl       : "" # apply repo name like "/myproject" if used under gh-pages branch, else (under master branch) just leave empty/blank
cover         : "" # image uri like logo/cover image for site seo
